# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee84d35749ae24e099cdffb283decd6c8adeb69a77495a852af778e51153b288a1a8a4b20349c1e2fb81dc40754a3089026085a74caf4516f65d35008321d0ab

test:
  secret_key_base: 8b096f3c5e8a701ba074823b4a997eaee4d228ff73705a516947a482be11ff28a7fa233095d2f2cb3466878efe546204e9dd1255cfeadba6c5de240b7e9c772e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
